sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: V6m1UgykVy6Bzo5dNGj4CP3tfmv176oTDgzJGPYN1a+NxItqCB2YI3nJONWAA1CwQ73ZE2Vymuca39dXQtK0Y+eBneKrEdK6m8T4IPyEBuo9KHtou15St0a6G+Y5sy/ZYjP6C6F7Sej1g0+R3ggZXIfmb2NTfyF5KBEoDGPdG5BkDuWwdmGY5e/TV6pTHz5fSp8MR3Ds7YiEKlQaLcHxv5q+lJJD9jC0uooTf8NQEtGeEg/Mruk4MMej78Hlk30UFN13FM/BmmpJT7eeDpOMOgF0r3Xzdz8HTjyiYGAl+rPD0JibdUAp6aFmpzBSzSQDdVn5vXtWYB4W4vRRkXI+IC2G3ReXJFlAy00TmEwrrLB4RPJbEYd2+cizKvQDeiCHdrzibvFkv8vmh8VD/N0P9tfloF0Y5DVH+ePVptTUrF1/Gr+ewZDWzVYQ8/BZEdjF33T57LrxkE4fVqHMQPEMXlFr7yn5Q1CdPyHKI3xH9I9rAeFhZxVeQU31m2sY/nyjvhaDjEh6dFJDxcePqlATsF/x5xY9K/Ri8oO0VS9T5Y6JK6jJl74NwcPvkrQ9dnoxvmHuawaxbgSlf26AOg5J46PZh06yq6d7jpF8v9kS7QyoUnH86cBxteK8gkE52eLqmvelLyWM0autT6EFcITdAA3TakKMiij3vRcl6DTP6qs=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: CYoPamGqb/5OCCW5bs2+tZxeidl0KDfwgHJCkz16CGyUchqGwSU8NG/ETAcDQuDgaWNYDRO2uF3iZpO9Lu6U7mmRpZczALq80TPu9FwNSK68B2N2+rRmASltP2g3nTQGUzK1mUXOWZvjMF7pUEBcqbmfMEZzoAV9nad2eQrvsPCgB4YgdHfvmxy6+2WDIyeIn3LYdkyjSktI3nNRlgrWv6o82y4joozlDfls8GvJAzbsyKqc9cL34AOweugn4icoo7Ll1Zd1A46FSlRUELzF+aF0kYiUOBin6jw54F7Tt+ZoFtHVvKjk89It2CsKNMcWmbKuaCFyiqLYk4NwtE6g6b3Jo443/qjCWAGMONigSjGMChePk+8wWKdXfJphdZdc6ios98VXNa+lPtaJIBuwXlHjP2jcMyC7rwglqRzmARBzGgy8fyQNt8qO9UrJsaVlj+QOeJQxZjZI2NhdL+EGgUwit5x5ZVeD96x6qS7RTEMsJAQIhZLYCe+5T21nKCeLLwY/ROwb2TmGk/u1LF2KIG28MxzZ8gJVTwQZRagGdHElFYSzf+cauw21vpTrJJ2r62rFeE9ENjWNYiGx64cojPGR8lgG2hIPpATJxN8S2tknGC616d5Wy2EgJ/hkg+qhSkOqNJ8z8gUK4rwUNcly/m+67S3ZzcXIu40w3W51joY=
